import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter/foundation.dart';

/// 多言語対応サービス
/// 
/// アプリ全体の言語設定を管理し、翻訳機能を提供します。
class LocalizationService extends ChangeNotifier {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  String _currentLanguage = 'ja'; // デフォルトは日本語
  
  String get currentLanguage => _currentLanguage;
  bool get isJapanese => _currentLanguage == 'ja';
  bool get isEnglish => _currentLanguage == 'en';

  /// 言語を設定
  Future<void> setLanguage(String languageCode) async {
    if (languageCode != _currentLanguage) {
      _currentLanguage = languageCode;
      await _saveLanguagePreference();
      notifyListeners();
    }
  }

  /// 保存された言語設定を読み込み
  Future<void> loadLanguagePreference() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString('language') ?? 'ja';
    notifyListeners();
  }

  /// 言語設定を保存
  Future<void> _saveLanguagePreference() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language', _currentLanguage);
  }

  /// 翻訳を取得
  String translate(String key) {
    return _translations[_currentLanguage]?[key] ?? key;
  }

  /// 翻訳データ
  static const Map<String, Map<String, String>> _translations = {
    'ja': {
      // アプリ共通
      'app_name': 'TalkOne',
      'ok': 'OK',
      'cancel': 'キャンセル',
      'save': '保存',
      'delete': '削除',
      'edit': '編集',
      'back': '戻る',
      'next': '次へ',
      'skip': 'スキップ',
      'loading': '読み込み中...',
      'error': 'エラー',
      'success': '成功',
      'failed': '失敗',
      
      // ホーム画面
      'home_title': 'Talk One',
      'home_greeting_1': 'こんにちは〜\n今日もがんばってるね！',
      'home_greeting_2': 'おつかれさま\nひと息つこ〜',
      'home_greeting_3': '今どんなアイディアが\n浮かんでる?',
      'home_start_voice_call': '音声通話を始める',
      'home_start_video_call': 'ビデオ通話を始める',
      'home_rate_label': 'RATE',
      'home_ai_rescue_550': '緊急AI救済モード（レート580まで）',
      'home_ai_rescue_700': 'AI救済モード（レート730まで）',
      'home_ai_rescue_850': 'AI練習モード（レート880まで）',
      
      // マッチング画面
      'matching_title': 'Talk One',
      'matching_rate_label': 'RATE',
      'matching_online_users': 'オンラインユーザー',
      'matching_in_progress': 'マッチング中',
      'matching_cancel': 'キャンセル',
      'matching_ai_conversation': 'AI との会話',
      'matching_ai_notification_550': 'AI（ずんだもん）とマッチング中 - レート580を超えると次の段階に進みます',
      'matching_ai_notification_700': 'AI（ずんだもん）とマッチング中 - レート730を超えると次の段階に進みます',
      'matching_ai_notification_850': 'AI（ずんだもん）とマッチング中 - レート880を超えると人間との通話に戻ります',
      
      // 通話画面
      'call_timer_label': '',
      'call_end_button': '通話終了',
      'call_topic_prefix': '話題：',
      
      // 評価画面
      'evaluation_title': '相手を評価してください',
      'evaluation_description': '今回の会話はいかがでしたか？',
      'evaluation_star_1': '★',
      'evaluation_star_2': '★★',
      'evaluation_star_3': '★★★',
      'evaluation_star_4': '★★★★',
      'evaluation_star_5': '★★★★★',
      'evaluation_submit': '評価を送信',
      'evaluation_submission_failed': '評価の送信に失敗しました',
      
      // 再マッチ画面
      'rematch_title': '通話完了',
      'rematch_call_ended': '通話が終了しました',
      'rematch_what_next': 'お疲れさまでした！\n次は何をしますか？',
      'rematch_button': 'もう一度話す',
      'rematch_match_again': 'もう一度マッチング',
      'rematch_home_button': 'ホームに戻る',
      'rematch_return_home': 'ホームに戻る',
      
      // 設定画面
      'settings_title': '設定',
      'settings_language': '言語',
      'settings_language_japanese': '日本語',
      'settings_language_english': 'English',
      'settings_theme': 'テーマ',
      'settings_profile': 'プロフィール',
      'settings_credits': 'クレジット',
      
      // プロフィール画面
      'profile_title': 'プロフィール',
      'profile_nickname': 'ニックネーム',
      'profile_gender': '性別',
      'profile_birthday': '誕生日(他の人には公開されません)',
      'profile_ai_memory': 'AIに知ってほしいこと',
      'profile_comment': 'みんなに一言',
      'profile_gender_male': '男性',
      'profile_gender_female': '女性',
      'profile_gender_other': 'その他',
      'profile_gender_not_specified': '回答しない',
      'profile_save_success': '保存しました',
      'profile_save_failed': '保存に失敗しました。しばらく経ってから再度お試しください。',
      'profile_account_info': 'アカウント情報',
      'profile_apple_account': 'Appleアカウント',
      'profile_google_account': 'Googleアカウント',
      'profile_guest_account': 'ゲストアカウント',
      'profile_sign_in_with_apple': 'Apple IDでサインイン中',
      'profile_data_transfer_message': 'AIとの会話履歴が機種変更時も引き継がれます',
      'profile_data_loss_warning': '機種変更時にデータが失われる可能性があります',
      'profile_upgrade_to_google': 'Googleアカウントにアップグレード',
      'profile_upgrade_to_apple': 'Apple IDにアップグレード',
      'profile_sign_out': 'サインアウト',
      'profile_sign_out_title': 'サインアウト',
      'profile_sign_out_message': 'サインアウトしますか？',
      'profile_sign_out_guest_warning': 'ゲストアカウントのデータは失われます。',
      'profile_sign_out_failed': 'サインアウトに失敗しました: ',
      'profile_upgrade_success': 'Googleアカウントへのアップグレードが完了しました',
      'profile_upgrade_cancelled': 'アップグレードがキャンセルされました',
      'profile_upgrade_failed': 'アップグレードに失敗しました',
      'profile_apple_upgrade_success': 'Apple IDへのアップグレードが完了しました',
      'profile_apple_account_exists': 'このApple IDは既に別の方法で登録されています。',
      'profile_upgrade_timeout': 'ログインがタイムアウトしました。ネットワーク接続を確認して再度お試しください。',
      'profile_upgrade_cancel_message': 'ログインがキャンセルされました',
      'profile_upgrade_network_error': 'ネットワークエラーが発生しました。接続を確認してください。',
      'profile_upgrade_account_exists': 'このGoogleアカウントは既に別の方法で登録されています。',
      'profile_upgrade_credential_in_use': 'この認証情報は既に使用されています。',
      'profile_upgrade_general_error': 'ログインに失敗しました。しばらく経ってから再度お試しください。',
      'profile_apple_upgrade_preparing': 'Apple IDでのアップグレードは準備中です',
      'profile_sign_in_required': 'サインインが必要です',
      'profile_gender_select_hint': '選択してください',
      'profile_birthday_select_hint': '選択してください',
      'profile_delete_title': 'プロフィールメッセージを削除',
      'profile_delete_message': 'プロフィールメッセージを削除しますか？この操作により、ニックネーム、コメント、AIメモリーがリセットされます。',
      'profile_delete_confirm': '削除する',
      'profile_delete_button': 'プロフィールメッセージを削除',
      'profile_delete_success': 'プロフィールメッセージを削除しました',
      'profile_delete_failed': 'プロフィールメッセージの削除に失敗しました',
      
      // 履歴画面
      'history_title': '通話履歴',
      'history_empty': '通話履歴がありません',
      'history_with_ai': 'AI',
      'history_today': '今日',
      'history_yesterday': '昨日',
      'history_days_ago': '日前',
      'history_call_duration': '通話時間',
      'history_your_rating': 'あなたの評価',
      'history_partner_rating': '相手の評価',
      
      // AI チャット画面
      'ai_chat_title': 'AI チャット',
      'ai_chat_input_hint': 'AIとチャットしてみよう...',
      'ai_chat_listening': '音声認識中...',
      'ai_chat_initializing': '初期化中...',
      'ai_chat_empty_message': '会話を始めましょう！',
      'ai_chat_empty_description': 'メッセージ入力または音声で話しかけてください',
      'ai_chat_connection_status_ok': 'Firebase AI Gemini 2.5 Flash (Vertex AI) 接続済み',
      'ai_chat_connection_status_error': 'Firebase AI 接続エラー - 設定確認',
      
      // エラーメッセージ
      'error_network': 'ネットワークエラーが発生しました',
      'error_permission': '権限が必要です',
      'error_unknown': '不明なエラーが発生しました',
      
      // 通報関連
      'report_title': '通報',
      'report_reason': '通報理由',
      'report_details': '詳細',
      'report_submit': '通報する',
      'report_success': '通報を受け付けました',
      
      // 通報ダイアログ（音声通話画面）
      'report_dialog_title': '{partnerName} を通報',
      'report_dialog_message': '不適切な行為の理由を選択してください：',
      'report_dialog_warning': '通報すると相手を自動ブロックし、今後マッチングしません',
      'report_category_harassment': 'ハラスメント',
      'report_category_harassment_desc': '相手からの嫌がらせや脅迫',
      'report_category_inappropriate_speech': '不適切な発言',
      'report_category_inappropriate_speech_desc': 'わいせつ・暴力的な内容',
      'report_category_spam': '迷惑行為',
      'report_category_spam_desc': '広告・スパム・営業勧誘',
      'report_category_discrimination': '差別・誹謗中傷',
      'report_category_discrimination_desc': '差別的発言や人格攻撃',
      'report_category_impersonation': 'なりすまし',
      'report_category_impersonation_desc': '偽の身分での利用',
      'report_category_other': 'その他',
      'report_category_other_desc': '上記以外の問題',
      'report_success_message': '通報しました。相手をブロックしました。',
      'report_failed_message': '通報に失敗しました',
      
      // AI プリコール画面
      'ai_precall_title': 'AI練習モード',
      'ai_precall_countdown': '音声チャット開始まで...',
      'ai_precall_skip': 'スキップ',
      
      // 追加翻訳
      'block_user': 'このユーザーをブロック',
      'partner_profile': '相手のプロフィール',
      'call_history': '通話履歴',
      'my_rating': '私の評価',
      'date': '日付',
      'delete_account': 'アカウント削除',
      'notifications': '通知',
      'error_occurred': 'エラーが発生しました',
      'waiting_users': 'マッチング待ちのユーザー',
      'matching_cancelled': 'マッチングがキャンセルされました',
      'conversation_screen': '会話画面',
      'call_ended': '通話終了',
      
      // プリコール画面
      'approve': '承認',
      'reject': '拒否',
      
      // パートナープロフィール画面
      'report_user': 'ユーザーを通報',
      'block_confirm_title': 'ユーザーをブロック',
      'block_confirm_message': 'このユーザーをブロックしますか？今後マッチングされなくなります。',
      'block_success': 'ユーザーをブロックしました',
      'block_failed': 'ブロックに失敗しました',
      
      // アカウント削除
      'delete_account_title': 'アカウント削除',
      'delete_account_message': '本当にアカウントを削除しますか？この操作は取り消せません。',
      'delete_account_confirm': '削除する',
      
      // 通知メッセージ
      'notification_empty': '通知はありません',
      'notification_new_match': '新しいマッチが見つかりました',
      'notification_call_request': '通話リクエストがあります',
      
      // エラーメッセージ
      'error_loading_profile': 'プロフィールの読み込みに失敗しました',
      'error_matching': 'マッチングエラーが発生しました',
      'error_call_failed': '通話接続に失敗しました',
      
      // 通知画面
      'notification_title': '通知',
      'notification_mark_all_read': '全て既読にする',
      'notification_close': '閉じる',
      'notification_delete_success': '通知を削除しました',
      'notification_mark_all_read_success': '全ての通知を既読にしました',
      'notification_error_occurred': 'エラーが発生しました',
      'notification_error_prefix': 'エラー: ',
      'notification_empty_description': '新しい通知があると、ここに表示されます',
      'notification_delete_title': '通知を削除',
      'notification_delete_message': 'この通知を削除しますか？',
      'notification_delete_confirm': '削除',
      'notification_version_create': 'Ver 1.0.1通知を作成',
      'notification_version_create_success': 'Ver 1.0.1通知を作成しました',
      
      // マッチング画面
      'matching_waiting_users': 'マッチング待ちのユーザー：{count}人',
      'ai_conversation_button': '{aiName}と会話',
      'ai_rescue_level_3': 'AI救済モード（レベル3）- ずんだもんとマッチング',
      'ai_rescue_level_3_ongoing': 'AI救済継続中（レベル3）- ずんだもんとマッチング',
      'ai_rescue_level_2': 'AI救済モード（レベル2）- ずんだもんとマッチング',
      'ai_rescue_level_2_ongoing': 'AI救済継続中（レベル2）- ずんだもんとマッチング',
      'ai_rescue_level_1': 'AI救済モード（レベル1）- ずんだもんとマッチング',
      'ai_rescue_level_1_ongoing': 'AI救済継続中（レベル1）- ずんだもんとマッチング',
      
      // 通話画面
      'call_connection_status_connecting': '接続中...',
      'call_connection_status_connected': '通話中',
      'call_connection_status_waiting': '相手を待機中',
      'call_connection_status_error': '接続エラー',
      'call_connection_status_disconnected': '未接続',
      'call_emergency_report_title': '緊急通報',
      'call_emergency_report_message': 'この相手を通報しますか？\n\n通報すると即座に通話が終了し、相手のプロフィール画面に移動します。',
      'call_emergency_report_submit': '通報する',
      'call_emergency_report_error': '緊急通報の処理中にエラーが発生しました。',
      
      // 評価画面
      'evaluation_tap_to_view_profile': 'タップして相手のプロフィールを表示',
      'evaluation_rate_conversation': '今の通話を評価してください',
      'evaluation_submitting': '評価を送信中...',
      'evaluation_very_bad': 'とても悪い',
      'evaluation_bad': '悪い',
      'evaluation_average': '普通',
      'evaluation_good': '良い',
      'evaluation_very_good': 'とても良い',
      
      // プリコール画面
      'precall_nickname_label': 'ニックネーム',
      'precall_gender_label': '性別',
      'precall_default_name': 'My Name',
      'precall_default_gender': '回答しない',
      'precall_loading': 'プロフィールを読み込み中...',
      'precall_greeting_comment': 'よろしくお願いします！',
      'precall_approve': '承認',
      'precall_reject': '拒否',
      'precall_skip': 'スキップ',
      
      // 設定画面
      'settings_voice_character': '音声キャラクター',
      'settings_achievement_section': '実績',
      'settings_delete_account': 'アカウント削除',
      'settings_achievement_hall_of_fame': '殿堂入り',
      'settings_achievement_gold': '金メダル',
      'settings_achievement_silver': '銀メダル',
      'settings_achievement_bronze': '銅メダル',
      'settings_achievement_beginner': 'ビギナー',
      'settings_all_features_unlocked': 'すべての機能が解禁されています',
      'settings_voicevox_unlocked': 'VOICEVOX機能が解禁されています',
      'settings_voicevox_requirement': 'レーティング1500以上でVOICEVOX解禁',
      'settings_basic_features_only': '基本機能のみ',
      'settings_current_level': '{level}',
      'settings_current_rating': 'レーティング:\n{rating}',
      'settings_next_target': '次の目標: {target}',
      'settings_points_remaining': '残り{points}ポイント',
      'settings_unlocked_features': '解禁機能: {features}',
      'settings_achievement_list': '実績レベル一覧',
      'settings_delete_account_confirm': 'この画面からアカウント削除を押すと、ログアウトされるだけでなく、これまでのレートとAI VOICEVOXの人格と会話が削除されます。本当によろしいですか？',
      'settings_delete_account_button': '削除する',
      'settings_rate_requirement_not_met': 'レートの条件を満たしてください。',
      'settings_agent_changed': 'エージェントを{characterName}に変更しました。',
      
      // 履歴画面
      'history_screen_title': '通話履歴',
      'history_empty_message': '通話履歴がありません',
      'history_empty_subtitle': '最初の通話を始めてみましょう！',
      'history_evaluation_dialog_title': '{partnerName}との通話評価',
      'history_your_rating_label': 'あなたの評価:',
      'history_call_duration_label': '通話時間:',
      'history_call_datetime_label': '通話日時:',
      'history_my_rating_prefix': '私の評価: ',
      'history_no_rating_text': '未評価',
      'history_blocked_status_text': 'ブロック中',
      'history_ai_label_text': 'AI',
      
      // パートナープロフィール画面
      'partner_profile_title': '相手のプロフィール',
      'partner_profile_nickname': 'ニックネーム',
      'partner_profile_gender': '性別',
      'partner_profile_comment': '一言コメント',
      'partner_profile_default_user': 'ユーザー',
      'partner_profile_default_unset': '未設定',
      'partner_profile_default_greeting': 'よろしくお願いします！',
      'partner_profile_report_button': 'この相手を通報する',
      'partner_profile_report_submitting': '通報送信中...',
      'partner_profile_report_title': '相手を通報',
      'partner_profile_report_reason': '通報理由を選択してください',
      'partner_profile_report_inappropriate': '不適切な発言',
      'partner_profile_report_harassment': '嫌がらせ',
      'partner_profile_report_spam': 'スパム行為',
      'partner_profile_report_other': 'その他',
      'partner_profile_report_details': '詳細（任意）',
      'partner_profile_report_details_hint': '具体的な内容を記入してください',
      'partner_profile_report_hint': '具体的な内容を記入してください',
      'partner_profile_report_cancel': 'キャンセル',
      'partner_profile_report_submit': '通報する',
      'partner_profile_report_sending': '通報送信中...',
      'partner_profile_block_title': 'ユーザーをブロック',
      'partner_profile_block_message': 'このユーザーをブロックすると、今後マッチングされなくなります。\nブロックしますか？',
      'partner_profile_block_cancel': 'キャンセル',
      'partner_profile_block_confirm': 'ブロックする',
      'partner_profile_block_button': 'ユーザーをブロック',
      'partner_profile_report_success': '通報を送信しました。24時間以内にサポートからのメールをお送りいたします。',
      'partner_profile_report_error': '通報の送信に失敗しました。しばらく経ってから再度お試しください。',
      'partner_profile_block_success': 'ユーザーをブロックしました。今後このユーザーとマッチングされることはありません。',
      'partner_profile_block_error': 'ブロックに失敗しました。再度お試しください。',
      
      // EULA画面
      'eula_title': 'エンドユーザーライセンス契約（EULA）',
      'eula_content_title': 'TalkOne エンドユーザーライセンス契約（EULA）',
      'eula_scroll_instruction': '利用規約を最後まで読んでください',
      'eula_agreement_checkbox': '上記の利用規約に同意します',
      'eula_disagree_button': '同意しない',
      'eula_agree_button': '同意してアプリを開始',
      'eula_language_switch': '言語切り替え',
      'eula_japanese': '日本語',
      'eula_english': 'English',
      'eula_exit_dialog_title': 'アプリを終了しますか？',
      'eula_exit_dialog_message': '利用規約に同意しない場合、アプリを使用できません。',
      'eula_exit_dialog_cancel': 'キャンセル',
      'eula_exit_dialog_exit': '終了',
      
      // AI移行画面
      'ai_pre_call_practice_mode': 'AI練習モード',
      'ai_pre_call_assistant': 'AI アシスタント',
      'ai_pre_call_countdown_text': '音声チャット開始まで...',
      'ai_pre_call_skip': 'スキップ',
      
      // アチーブメント
      'achievement_bronze': 'ブロンズ',
      'achievement_copper': '銅メダル',
      'achievement_silver': '銀メダル',
      'achievement_gold': '金メダル',
      'achievement_hall_of_fame': '殿堂入り',
      'achievement_voicevox_unlocked': 'VOICEVOX解禁',
      'achievement_all_features_unlocked': 'すべての機能解禁',
      
      // 共通要素
      'common_close': '閉じる',
      'common_confirm': '確認',
      'common_yes': 'はい',
      'common_no': 'いいえ',
      'common_retry': '再試行',
      'common_continue': '続ける',
      'common_finish': '完了',
      'common_loading': '読み込み中...',
      'common_unknown': 'Unknown',
      
      // 会話テーマ（35種類）
      'theme_1': '🎯 自己紹介・自己理解系',
      'theme_2': '最近ハマってること',
      'theme_3': '好きな食べ物／嫌いな食べ物',
      'theme_4': '休日の過ごし方',
      'theme_5': '朝型？夜型？',
      'theme_6': '自分の性格を一言で言うと？',
      'theme_7': '今までで一番頑張ったこと',
      'theme_8': '最近ちょっと変わったこと',
      'theme_9': '尊敬している人',
      'theme_10': '自分の中のマイルール',
      'theme_11': '子どもの頃の夢',
      'theme_12': '💬 日常会話・雑談系',
      'theme_13': '最近観た映画／ドラマ',
      'theme_14': '今日の天気、好き？',
      'theme_15': '通勤・通学時間の過ごし方',
      'theme_16': '最近びっくりしたこと',
      'theme_17': '今、部屋にあるものでお気に入りは？',
      'theme_18': '最近の「ちょっと嬉しかったこと」',
      'theme_19': '毎日欠かさずやってること',
      'theme_20': '今食べたいもの',
      'theme_21': 'おすすめのアプリ／ツール',
      'theme_22': '今のスマホの待ち受け画面、どんなの？',
      'theme_23': '💭 意見交換・感情表現系',
      'theme_24': '幸せだなと思う瞬間は？',
      'theme_25': 'イライラしたとき、どうする？',
      'theme_26': '自分って変わってるなと思うとき',
      'theme_27': '友達ってどんな存在？',
      'theme_28': 'プレゼントするなら何を選ぶ？',
      'theme_29': 'あえて「何もしない時間」って必要？',
      'theme_30': '人から言われて嬉しかった言葉',
      'theme_31': '自分の中の「こだわり」って何？',
      'theme_32': '落ち込んだときの立ち直り方',
      'theme_33': 'やってみたいけど、ちょっと怖いこと',
      
      // ホーム画面追加
      'home_icon_select_title': 'アイコンを選択',
      'home_ai_rescue_warning_550': 'レート550以下のため、AI救済モード（レベル3）が発動中です',
      'home_ai_rescue_ongoing_580': 'AI救済モード中（レベル3）継続中です',
      'home_ai_rescue_warning_700': 'レート700以下のため、AI救済モード（レベル2）が発動中です',
      'home_ai_rescue_ongoing_730': 'AI救済モード中（レベル2）継続中です',
      'home_ai_rescue_warning_850': 'レート850以下のため、AI救済モード（レベル1）が発動中です',
      'home_ai_rescue_ongoing_880': 'AI救済モード中（レベル1）継続中です',
      'home_target_580': 'レート580を超えると次の段階に進みます',
      'home_target_730': 'レート730を超えると次の段階に進みます',
      'home_target_880': 'レート880を超えると人間との通話に戻ります',
      
      // 設定・クレジット画面追加
      'settings_debug_rating_title': 'デバッグ: レーティング変更',
      'settings_debug_current_rating': '現在のレーティング: {rating}',
      'settings_new_rating_hint': '新しいレーティング (0-5000)',
      'settings_rating_changed': 'レーティングを{rating}に変更しました',
      'settings_rating_range_error': '0から5000の間の数値を入力してください',
      'settings_level_bronze': 'ブロンズ',
      'settings_level_copper': '銅メダル',
      'settings_level_silver': '銀メダル',
      'settings_level_gold': '金メダル',
      'settings_level_hall_of_fame': '殿堂入り',
      'settings_voicevox_unlock': 'VOICEVOX解禁',
      'settings_all_features_unlock': 'すべての機能解禁',
      'settings_user_not_authenticated': 'ユーザーが認証されていません',
      'settings_account_delete_success': 'お使いのGoogle/Appleアカウントのアプリケーション内情報を削除しました。',
      'settings_account_delete_failed': 'アカウントの削除に失敗しました。再度お試しください。',
      'credit_title': 'クレジット表記',
      'credit_acknowledgments': '謝辞',
      'credit_contact_title': 'お問い合わせ',
      'credit_contact_description': 'ご質問・ご要望・不具合報告など\nお気軽にお問い合わせください',
      
      // アカウントリンク機能
      'settings_link_account_title': 'アカウント連携',
      'settings_link_account_description': 'Apple IDまたはGoogleアカウントと連携すると、機種変更時もデータが引き継がれます',
      'settings_link_apple': 'Apple IDと連携',
      'settings_link_google': 'Googleと連携',
      'settings_link_success_apple': 'Apple IDとの連携が完了しました',
      'settings_link_success_google': 'Googleアカウントとの連携が完了しました',
      'settings_link_error': '連携に失敗しました: {error}',
      'settings_privacy': 'プライバシー設定',

      // ログイン画面
      'login_app_name': 'TalkOne',
      'login_catchphrase': '1対1のボイスチャットで\n会話スキルを向上させよう',
      'login_google_button': 'Googleアカウントでサインイン',
      'login_apple_button': 'Apple IDでサインイン',
      'login_guest_button': 'ゲストでプレイ',
      'login_description': 'Apple IDまたはGoogleでサインインすると、\n機種変更時もAIとの会話履歴が引き継がれます\n\n※メールアドレスは一切収集しません（App Store準拠）',
      'login_google_success': 'Googleアカウントでサインインしました',
      'login_apple_success': 'Apple IDでサインインしました',
      'login_guest_success': 'ゲストとしてサインインしました',
      'login_cancelled': 'サインインがキャンセルされました',
      'login_failed': 'サインインに失敗しました',
    },
    
    'en': {
      // App Common
      'app_name': 'TalkOne',
      'ok': 'OK',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'back': 'Back',
      'next': 'Next',
      'skip': 'Skip',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'failed': 'Failed',
      
      // Home Screen
      'home_title': 'Talk One',
      'home_greeting_1': 'Hello!\nKeep up the good work today!',
      'home_greeting_2': 'Good job!\nTake a break',
      'home_greeting_3': 'What ideas are you\nthinking about?',
      'home_start_voice_call': 'Start Voice Call',
      'home_start_video_call': 'Start Video Call',
      'home_rate_label': 'RATE',
      'home_ai_rescue_550': 'Emergency AI Rescue Mode (Until Rate 580)',
      'home_ai_rescue_700': 'AI Rescue Mode (Until Rate 730)',
      'home_ai_rescue_850': 'AI Practice Mode (Until Rate 880)',
      
      // Matching Screen
      'matching_title': 'Talk One',
      'matching_rate_label': 'RATE',
      'matching_online_users': 'Online Users',
      'matching_in_progress': 'Matching...',
      'matching_cancel': 'Cancel',
      'matching_ai_conversation': 'AI Conversation',
      'matching_ai_notification_550': 'Matching with AI (Zundamon) - Advance to next stage when rate exceeds 580',
      'matching_ai_notification_700': 'Matching with AI (Zundamon) - Advance to next stage when rate exceeds 730',
      'matching_ai_notification_850': 'Matching with AI (Zundamon) - Return to human calls when rate exceeds 880',
      
      // Call Screen
      'call_timer_label': '',
      'call_end_button': 'End Call',
      'call_topic_prefix': 'Topic: ',
      
      // Evaluation Screen
      'evaluation_title': 'Rate Your Partner',
      'evaluation_description': 'How was this conversation?',
      'evaluation_star_1': '★',
      'evaluation_star_2': '★★',
      'evaluation_star_3': '★★★',
      'evaluation_star_4': '★★★★',
      'evaluation_star_5': '★★★★★',
      'evaluation_submit': 'Submit Rating',
      'evaluation_submission_failed': 'Failed to submit rating',
      
      // Rematch Screen
      'rematch_title': 'Call Completed',
      'rematch_call_ended': 'Call has ended',
      'rematch_what_next': 'Thank you for your time!\nWhat would you like to do next?',
      'rematch_button': 'Talk Again',
      'rematch_match_again': 'Match Again',
      'rematch_home_button': 'Back to Home',
      'rematch_return_home': 'Return to Home',
      
      // Settings Screen
      'settings_title': 'Settings',
      'settings_language': 'Language',
      'settings_language_japanese': '日本語',
      'settings_language_english': 'English',
      'settings_theme': 'Theme',
      'settings_profile': 'Profile',
      'settings_credits': 'Credits',
      
      // Profile Screen
      'profile_title': 'Profile',
      'profile_nickname': 'Nickname',
      'profile_gender': 'Gender',
      'profile_birthday': 'Birthday (Private)',
      'profile_ai_memory': 'What AI should know about you',
      'profile_comment': 'Message to everyone',
      'profile_gender_male': 'Male',
      'profile_gender_female': 'Female',
      'profile_gender_other': 'Other',
      'profile_gender_not_specified': 'Prefer not to say',
      'profile_save_success': 'Saved successfully',
      'profile_save_failed': 'Failed to save. Please try again later.',
      'profile_account_info': 'Account Information',
      'profile_apple_account': 'Apple Account',
      'profile_google_account': 'Google Account',
      'profile_guest_account': 'Guest Account',
      'profile_sign_in_with_apple': 'Signed in with Apple ID',
      'profile_data_transfer_message': 'AI conversation history will be preserved when changing devices',
      'profile_data_loss_warning': 'Data may be lost when changing devices',
      'profile_upgrade_to_google': 'Upgrade to Google Account',
      'profile_upgrade_to_apple': 'Upgrade to Apple ID',
      'profile_sign_out': 'Sign Out',
      'profile_sign_out_title': 'Sign Out',
      'profile_sign_out_message': 'Are you sure you want to sign out?',
      'profile_sign_out_guest_warning': 'Guest account data will be lost.',
      'profile_sign_out_failed': 'Failed to sign out: ',
      'profile_upgrade_success': 'Successfully upgraded to Google account',
      'profile_upgrade_cancelled': 'Upgrade cancelled',
      'profile_upgrade_failed': 'Upgrade failed',
      'profile_apple_upgrade_success': 'Successfully upgraded to Apple ID',
      'profile_apple_account_exists': 'This Apple ID is already registered with another method.',
      'profile_upgrade_timeout': 'Login timed out. Please check your network connection and try again.',
      'profile_upgrade_cancel_message': 'Login cancelled',
      'profile_upgrade_network_error': 'Network error occurred. Please check your connection.',
      'profile_upgrade_account_exists': 'This Google account is already registered with another method.',
      'profile_upgrade_credential_in_use': 'These credentials are already in use.',
      'profile_upgrade_general_error': 'Login failed. Please try again later.',
      'profile_apple_upgrade_preparing': 'Apple ID upgrade is being prepared',
      'profile_sign_in_required': 'Sign in required',
      'profile_gender_select_hint': 'Select',
      'profile_birthday_select_hint': 'Select',
      'profile_delete_title': 'Delete Profile Messages',
      'profile_delete_message': 'Delete profile messages? This will reset your nickname, comment, and AI memory.',
      'profile_delete_confirm': 'Delete',
      'profile_delete_button': 'Delete Profile Messages',
      'profile_delete_success': 'Profile messages deleted',
      'profile_delete_failed': 'Failed to delete profile messages',
      
      // History Screen
      'history_title': 'Call History',
      'history_empty': 'No call history',
      'history_with_ai': 'AI',
      'history_today': 'Today',
      'history_yesterday': 'Yesterday',
      'history_days_ago': ' days ago',
      'history_call_duration': 'Duration',
      'history_your_rating': 'Your Rating',
      'history_partner_rating': 'Partner\'s Rating',
      
      // AI Chat Screen
      'ai_chat_title': 'AI Chat',
      'ai_chat_input_hint': 'Chat with AI...',
      'ai_chat_listening': 'Listening...',
      'ai_chat_initializing': 'Initializing...',
      'ai_chat_empty_message': 'Let\'s start chatting!',
      'ai_chat_empty_description': 'Type a message or speak to chat',
      'ai_chat_connection_status_ok': 'Firebase AI Gemini 2.5 Flash (Vertex AI) Connected',
      'ai_chat_connection_status_error': 'Firebase AI Connection Error - Check Settings',
      
      // Error Messages
      'error_network': 'Network error occurred',
      'error_permission': 'Permission required',
      'error_unknown': 'Unknown error occurred',
      
      // Report Related
      'report_title': 'Report',
      'report_reason': 'Reason',
      'report_details': 'Details',
      'report_submit': 'Submit Report',
      'report_success': 'Report submitted successfully',
      
      // Report Dialog (Voice Call Screen)
      'report_dialog_title': 'Report {partnerName}',
      'report_dialog_message': 'Select the reason for inappropriate behavior:',
      'report_dialog_warning': 'Reporting will automatically block the user and prevent future matching',
      'report_category_harassment': 'Harassment',
      'report_category_harassment_desc': 'Harassment or threats from the user',
      'report_category_inappropriate_speech': 'Inappropriate Language',
      'report_category_inappropriate_speech_desc': 'Obscene or violent content',
      'report_category_spam': 'Spam/Solicitation',
      'report_category_spam_desc': 'Advertising, spam, or business solicitation',
      'report_category_discrimination': 'Discrimination',
      'report_category_discrimination_desc': 'Discriminatory remarks or personal attacks',
      'report_category_impersonation': 'Impersonation',
      'report_category_impersonation_desc': 'Using false identity',
      'report_category_other': 'Other',
      'report_category_other_desc': 'Issues not listed above',
      'report_success_message': 'Reported successfully. The user has been blocked.',
      'report_failed_message': 'Report failed',
      
      // AI Pre-call Screen
      'ai_precall_title': 'AI Practice Mode',
      'ai_precall_countdown': 'Voice chat starting in...',
      'ai_precall_skip': 'Skip',
      
      // Additional translations requested
      'block_user': 'Block this user',
      'partner_profile': 'Partner\'s Profile',
      'call_history': 'Call History',
      'my_rating': 'My Rating',
      'date': 'Date',
      'delete_account': 'Delete Account',
      'notifications': 'Notifications',
      'error_occurred': 'An error occurred',
      'waiting_users': 'Waiting for users',
      'matching_cancelled': 'Matching cancelled',
      'conversation_screen': 'Conversation Screen',
      'call_ended': 'Call Ended',
      
      // Pre-call screen
      'approve': 'Approve',
      'reject': 'Reject',
      
      // Partner profile screen
      'report_user': 'Report User',
      'block_confirm_title': 'Block User',
      'block_confirm_message': 'Are you sure you want to block this user? You will no longer be matched with them.',
      'block_success': 'User has been blocked',
      'block_failed': 'Failed to block user',
      
      // Account deletion
      'delete_account_title': 'Delete Account',
      'delete_account_message': 'Are you sure you want to delete your account? This action cannot be undone.',
      'delete_account_confirm': 'Delete',
      
      // Notification messages
      'notification_empty': 'No notifications',
      'notification_new_match': 'New match found',
      'notification_call_request': 'Incoming call request',
      
      // Error messages
      'error_loading_profile': 'Failed to load profile',
      'error_matching': 'Matching error occurred',
      'error_call_failed': 'Call connection failed',
      
      // Notification Screen
      'notification_title': 'Notifications',
      'notification_mark_all_read': 'Mark all as read',
      'notification_close': 'Close',
      'notification_delete_success': 'Notification deleted',
      'notification_mark_all_read_success': 'All notifications marked as read',
      'notification_error_occurred': 'An error occurred',
      'notification_error_prefix': 'Error: ',
      'notification_empty_description': 'New notifications will appear here',
      'notification_delete_title': 'Delete Notification',
      'notification_delete_message': 'Delete this notification?',
      'notification_delete_confirm': 'Delete',
      'notification_version_create': 'Create Ver 1.0.1 notification',
      'notification_version_create_success': 'Ver 1.0.1 notification created',
      
      // Matching Screen
      'matching_waiting_users': 'Waiting users: {count}',
      'ai_conversation_button': 'Chat with {aiName}',
      'ai_rescue_level_3': 'AI Rescue Mode (Level 3) - Matching with Zundamon',
      'ai_rescue_level_3_ongoing': 'AI Rescue Ongoing (Level 3) - Matching with Zundamon',
      'ai_rescue_level_2': 'AI Rescue Mode (Level 2) - Matching with Zundamon',
      'ai_rescue_level_2_ongoing': 'AI Rescue Ongoing (Level 2) - Matching with Zundamon',
      'ai_rescue_level_1': 'AI Rescue Mode (Level 1) - Matching with Zundamon',
      'ai_rescue_level_1_ongoing': 'AI Rescue Ongoing (Level 1) - Matching with Zundamon',
      
      // Call Screen
      'call_connection_status_connecting': 'Connecting...',
      'call_connection_status_connected': 'Connected',
      'call_connection_status_waiting': 'Waiting for partner',
      'call_connection_status_error': 'Connection Error',
      'call_connection_status_disconnected': 'Disconnected',
      'call_emergency_report_title': 'Emergency Report',
      'call_emergency_report_message': 'Report this user?\n\nThis will immediately end the call and redirect to their profile page.',
      'call_emergency_report_submit': 'Report',
      'call_emergency_report_error': 'Error occurred while processing emergency report.',
      
      // Evaluation Screen
      'evaluation_tap_to_view_profile': 'Tap to view partner\'s profile',
      'evaluation_rate_conversation': 'Rate this conversation',
      'evaluation_submitting': 'Submitting rating...',
      'evaluation_very_bad': 'Very Bad',
      'evaluation_bad': 'Bad',
      'evaluation_average': 'Average',
      'evaluation_good': 'Good',
      'evaluation_very_good': 'Very Good',
      
      // Pre-call Screen
      'precall_nickname_label': 'Nickname',
      'precall_gender_label': 'Gender',
      'precall_default_name': 'My Name',
      'precall_default_gender': 'Prefer not to say',
      'precall_loading': 'Loading profile...',
      'precall_greeting_comment': 'Nice to meet you!',
      'precall_approve': 'Approve',
      'precall_reject': 'Reject',
      'precall_skip': 'Skip',
      
      // Settings Screen
      'settings_voice_character': 'Voice Character',
      'settings_achievement_section': 'Achievements',
      'settings_delete_account': 'Delete Account',
      'settings_achievement_hall_of_fame': 'Hall of Fame',
      'settings_achievement_gold': 'Gold Medal',
      'settings_achievement_silver': 'Silver Medal',
      'settings_achievement_bronze': 'Bronze Medal',
      'settings_achievement_beginner': 'Beginner',
      'settings_all_features_unlocked': 'All features unlocked',
      'settings_voicevox_unlocked': 'VOICEVOX features unlocked',
      'settings_voicevox_requirement': 'VOICEVOX unlocks at rating 1500+',
      'settings_basic_features_only': 'Basic features only',
      'settings_current_level': '{level}',
      'settings_current_rating': 'Rating:\n{rating}',
      'settings_next_target': 'Next Target: {target}',
      'settings_points_remaining': '{points} points remaining',
      'settings_unlocked_features': 'Unlocked Features: {features}',
      'settings_achievement_list': 'Achievement Levels',
      'settings_delete_account_confirm': 'Deleting your account will sign you out and permanently delete your rating, AI VOICEVOX personality data, and conversation history. Are you sure?',
      'settings_delete_account_button': 'Delete',
      'settings_rate_requirement_not_met': 'Rating requirement not met.',
      'settings_agent_changed': 'Agent changed to {characterName}.',
      
      // History Screen
      'history_screen_title': 'Call History',
      'history_empty_message': 'No call history',
      'history_empty_subtitle': 'Start your first call!',
      'history_evaluation_dialog_title': 'Call with {partnerName}',
      'history_your_rating_label': 'Your rating:',
      'history_call_duration_label': 'Duration:',
      'history_call_datetime_label': 'Date & Time:',
      'history_my_rating_prefix': 'My Rating: ',
      'history_no_rating_text': 'Not rated',
      'history_blocked_status_text': 'Blocked',
      'history_ai_label_text': 'AI',
      
      // Partner Profile Screen
      'partner_profile_title': 'Partner\'s Profile',
      'partner_profile_nickname': 'Nickname',
      'partner_profile_gender': 'Gender',
      'partner_profile_comment': 'Message',
      'partner_profile_default_user': 'User',
      'partner_profile_default_unset': 'Not set',
      'partner_profile_default_greeting': 'Nice to meet you!',
      'partner_profile_report_button': 'Report this user',
      'partner_profile_report_submitting': 'Submitting report...',
      'partner_profile_report_title': 'Report User',
      'partner_profile_report_reason': 'Select report reason',
      'partner_profile_report_inappropriate': 'Inappropriate language',
      'partner_profile_report_harassment': 'Harassment',
      'partner_profile_report_spam': 'Spam',
      'partner_profile_report_other': 'Other',
      'partner_profile_report_details': 'Details (optional)',
      'partner_profile_report_details_hint': 'Please describe the specific issue',
      'partner_profile_report_hint': 'Please describe the specific issue',
      'partner_profile_report_cancel': 'Cancel',
      'partner_profile_report_submit': 'Submit Report',
      'partner_profile_report_sending': 'Sending report...',
      'partner_profile_block_title': 'Block User',
      'partner_profile_block_message': 'Blocking this user will prevent future matches.\nProceed with blocking?',
      'partner_profile_block_cancel': 'Cancel',
      'partner_profile_block_confirm': 'Block',
      'partner_profile_block_button': 'Block User',
      'partner_profile_report_success': 'Report submitted. You will receive a support email within 24 hours.',
      'partner_profile_report_error': 'Failed to submit report. Please try again later.',
      'partner_profile_block_success': 'User has been blocked. You will no longer be matched with this user.',
      'partner_profile_block_error': 'Failed to block user. Please try again.',
      
      // EULA Screen
      'eula_title': 'End User License Agreement (EULA)',
      'eula_content_title': 'TalkOne End User License Agreement (EULA)',
      'eula_scroll_instruction': 'Please scroll to the end of the terms',
      'eula_agreement_checkbox': 'I agree to the above terms of service',
      'eula_disagree_button': 'Disagree',
      'eula_agree_button': 'Agree and Start App',
      'eula_language_switch': 'Language',
      'eula_japanese': '日本語',
      'eula_english': 'English',
      'eula_exit_dialog_title': 'Exit App?',
      'eula_exit_dialog_message': 'You cannot use the app without agreeing to the terms of service.',
      'eula_exit_dialog_cancel': 'Cancel',
      'eula_exit_dialog_exit': 'Exit',
      
      // AI Pre-Call Screen
      'ai_pre_call_practice_mode': 'AI Practice Mode',
      'ai_pre_call_assistant': 'AI Assistant',
      'ai_pre_call_countdown_text': 'Starting voice chat in...',
      'ai_pre_call_skip': 'Skip',
      
      // Common Elements
      'common_close': 'Close',
      'common_confirm': 'Confirm',
      'common_yes': 'Yes',
      'common_no': 'No',
      'common_retry': 'Retry',
      'common_continue': 'Continue',
      'common_finish': 'Finish',
      'common_loading': 'Loading...',
      'common_unknown': 'Unknown',
      
      // Conversation Themes (35 topics)
      'theme_1': '🎯 Self-introduction & Understanding',
      'theme_2': 'What are you into lately?',
      'theme_3': 'Favorite / Least favorite foods',
      'theme_4': 'How do you spend weekends?',
      'theme_5': 'Morning person or night owl?',
      'theme_6': 'Describe your personality in one word',
      'theme_7': 'What have you worked hardest for?',
      'theme_8': 'Something that changed recently',
      'theme_9': 'Someone you respect',
      'theme_10': 'Your personal rules',
      'theme_11': 'Childhood dreams',
      'theme_12': '💬 Daily Chat & Small Talk',
      'theme_13': 'Recent movies/TV shows you watched',
      'theme_14': 'Do you like today\'s weather?',
      'theme_15': 'How do you spend commute time?',
      'theme_16': 'Something surprising that happened recently',
      'theme_17': 'Favorite thing in your room right now',
      'theme_18': 'Recent small moments of happiness',
      'theme_19': 'Something you do every day',
      'theme_20': 'What do you want to eat now?',
      'theme_21': 'Recommended apps/tools',
      'theme_22': 'What\'s your phone wallpaper like?',
      'theme_23': '💭 Opinion Exchange & Emotions',
      'theme_24': 'When do you feel happiest?',
      'theme_25': 'What do you do when frustrated?',
      'theme_26': 'When do you think you\'re unique?',
      'theme_27': 'What do friends mean to you?',
      'theme_28': 'What would you choose as a gift?',
      'theme_29': 'Is "doing nothing" time necessary?',
      'theme_30': 'Kind words that made you happy',
      'theme_31': 'What are you particular about?',
      'theme_32': 'How do you recover from setbacks?',
      'theme_33': 'Something you want to try but find scary',
      
      // Home Screen Additional
      'home_icon_select_title': 'Select Icon',
      'home_ai_rescue_warning_550': 'AI Rescue Mode (Level 3) active due to rating below 550',
      'home_ai_rescue_ongoing_580': 'AI Rescue Mode (Level 3) ongoing',
      'home_ai_rescue_warning_700': 'AI Rescue Mode (Level 2) active due to rating below 700',
      'home_ai_rescue_ongoing_730': 'AI Rescue Mode (Level 2) ongoing',
      'home_ai_rescue_warning_850': 'AI Rescue Mode (Level 1) active due to rating below 850',
      'home_ai_rescue_ongoing_880': 'AI Rescue Mode (Level 1) ongoing',
      'home_target_580': 'Advance to next stage when rating exceeds 580',
      'home_target_730': 'Advance to next stage when rating exceeds 730',
      'home_target_880': 'Return to human calls when rating exceeds 880',
      
      // Settings & Credit Screen Additional
      'settings_debug_rating_title': 'Debug: Rating Change',
      'settings_debug_current_rating': 'Current Rating: {rating}',
      'settings_new_rating_hint': 'New Rating (0-5000)',
      'settings_rating_changed': 'Rating changed to {rating}',
      'settings_rating_range_error': 'Please enter a number between 0 and 5000',
      'settings_level_bronze': 'Bronze',
      'settings_level_copper': 'Copper Medal',
      'settings_level_silver': 'Silver Medal',
      'settings_level_gold': 'Gold Medal',
      'settings_level_hall_of_fame': 'Hall of Fame',
      'settings_voicevox_unlock': 'VOICEVOX Unlocked',
      'settings_all_features_unlock': 'All Features Unlocked',
      'settings_user_not_authenticated': 'User not authenticated',
      'settings_account_delete_success': 'App data removed from your Google/Apple account.',
      'settings_account_delete_failed': 'Failed to delete account. Please try again.',
      'credit_title': 'Credits',
      'credit_acknowledgments': 'Acknowledgments',
      'credit_contact_title': 'Contact Us',
      'credit_contact_description': 'Questions, requests, bug reports, etc.\nFeel free to contact us',
      
      // Account Linking Feature
      'settings_link_account_title': 'Link Account',
      'settings_link_account_description': 'Link with Apple ID or Google Account to preserve data when changing devices',
      'settings_link_apple': 'Link with Apple ID',
      'settings_link_google': 'Link with Google',
      'settings_link_success_apple': 'Successfully linked with Apple ID',
      'settings_link_success_google': 'Successfully linked with Google Account',
      'settings_link_error': 'Failed to link: {error}',
      'settings_privacy': 'Privacy Settings',

      // Login Screen
      'login_app_name': 'TalkOne',
      'login_catchphrase': 'Improve your conversation skills\nwith 1-on-1 voice chat',
      'login_google_button': 'Sign in with Google',
      'login_apple_button': 'Sign in with Apple ID',
      'login_guest_button': 'Play as Guest',
      'login_description': 'Sign in with Apple ID or Google to preserve\nAI conversation history when changing devices\n\n*We do not collect email addresses (App Store compliant)',
      'login_google_success': 'Signed in with Google',
      'login_apple_success': 'Signed in with Apple ID',
      'login_guest_success': 'Signed in as guest',
      'login_cancelled': 'Sign in cancelled',
      'login_failed': 'Sign in failed',
      
      // Achievements
      'achievement_bronze': 'Bronze',
      'achievement_copper': 'Copper Medal',
      'achievement_silver': 'Silver Medal',
      'achievement_gold': 'Gold Medal',
      'achievement_hall_of_fame': 'Hall of Fame',
      'achievement_voicevox_unlocked': 'VOICEVOX Unlocked',
      'achievement_all_features_unlocked': 'All Features Unlocked',
    },
  };
}