apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: agora-token-service
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/YOUR_PROJECT_ID/agora-token-service
        ports:
        - containerPort: 8080
        env:
        - name: AGORA_APP_ID
          value: "4067eac9200f4aebb0fcf1b190eabd7d"
        - name: AGORA_APP_CERTIFICATE
          value: "YOUR_APP_CERTIFICATE_HERE"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"